### ISSUE TITLE
Add stat function

### ISSUE THREAD

**Issue by fjakobs** [c9/vfs#1]
this is esp necessary to check if a path points to a directory or a to a file

**Comment by fjakobs** [comment]
stat should return the same json as the items returned by readdir

**Comment by creationix** [comment]
For now this can mostly be accomplished by doing a readfile with {head:true} or make a HEAD http request.

I think it's a fine API to add to the vfs interface.  Not sure what the HTTP interface would be, maybe another special POST command, or one of the webdav verbs?

**Comment by fjakobs** [comment]
What I used before was a combination of readfile and readdir with head:true because I did not know if I deal with a file or a directory. However this was quite cumbersome.

What about the webdav PROPFIND method?

**Comment by fjakobs** [comment]
we use propfind and return the stat object as meta
