### ISSUE TITLE
in stat when we have a symlink should include the stat of the target

### ISSUE THREAD

**Issue by fjakobs** [c9/vfs#13]
esp. I need to know if it points to a directory or to a file

**Comment by creationix** [comment]
Including the stat of the target is dangerous if using fstat or stat.  But we could resolve the symlink manually after doing lstat and then if it's safe do a stat.  I agree that knowing the mime of the target (and maybe the other data) is useful.

**Comment by fjakobs** [comment]
realpath the file in the symling and add the stat of that to the result if it is in the tree

**Comment by creationix** [comment]
Fixed in fb4750da29ebee69c1ed9d8dbed6fd39faf3ae86.  Symlink entries now have an extra `linkStat` property with the stat of what they point to (if the target is within the chroot)
