### ISSUE TITLE
add modifiedSince function

### ISSUE THREAD

**Issue by fjakobs** [c9/vfs#15]
add something like

``` javascript
vfs.modifiedSince([list, of. files, or, directories], timestamp, function(err, filesFromListWhichHaveBeenChangedSinceTimestamp) {
});
```

as basis for the IDE's file watcher.

**Comment by creationix** [comment]
Should this just be the filenames or directories that have changed, or their whole stat objects?

**Comment by fjakobs** [comment]
I think we need to have the stats because when a directory changes we have to update the tree. We also need to know if items in the list have been removed. Obviously those don't have stats. I think we could handle this similar to the readdir function.

**Comment by creationix** [comment]
So the input to this can be fairly large.  What if the vfs function took a single path and returned a filtered version of what readdir does?  We could pipeline the list of directories and files and get back a stream of streams?

**Comment by creationix** [comment]
This was added a while back, but I forgot to close this.
