### ISSUE TITLE
rmdir should have option for recursive delete

### ISSUE THREAD

**Issue by fjakobs** [c9/vfs#4]

**Comment by creationix** [comment]
What should the behavior be if a directory in the source tree is not writable (and thus it's contents can't be deleted)?

Should the whole operation fail early on error, should it check for possible errors before starting real work, should it ignore errors as best and continue working where possible?

**Comment by fjakobs** [comment]
Doing the check before could be quite expensive. Right now we just shell out to "rm -rf". So if it resembles that it would be fine.

**Comment by fjakobs** [comment]
we'll just delete everything we can and if there was an error forward that in the error callback
