### ISSUE TITLE
getent is not available on OSX

### ISSUE THREAD

**Issue by fjakobs** [c9/vfs#5]

**Comment by creationix** [comment]
The latest node release now has a fix for gid/uid on spawn so we can remove this ugly hack if we bump the minimum node version in package.json.  I don't want to add another workaround for osx, it's not worth the effort.

**Comment by fjakobs** [comment]
I agree.

**Comment by fjakobs** [comment]
add setuid and setgid to child

**Comment by creationix** [comment]
Removed hack and bumped minimum node version in package.json.
