### ISSUE TITLE
add killtree

### ISSUE THREAD

**Issue by fjakobs** [c9/vfs#6]
we have to make sure that no zombie processes remain running after a kill. Something like https://github.com/c9/runjs/blob/master/run.js#L109

**Comment by creationix** [comment]
How portable is `ps` as used in that code?  Obviously it won't work on windows and we'll need a story for that, but is it otherwise compatible?

**Comment by fjakobs** [comment]
I've tested it on OSX and Solaris. I'd be surprised if it doesn't work on Linux.

**Comment by fjakobs** [comment]
replace child.kill with child.killtree in the local version
