### ISSUE TITLE
implement stream.setEncoding() for remote streams

### ISSUE THREAD

**Issue by fjakobs** [c9/vfs#7]
in my code I have

``` javascript
self.$stream.setEncoding("utf8");
```

Can this be supported? Does it make sense?

**Comment by fjakobs** [comment]
this is for `connect()`. It would best to add this as option to this function.

**Comment by creationix** [comment]
For connect, we want an `encoding` option that calls setEncoding when the stream is created.  For spawn we want `stderrEncoding` and `stderrEncoding` options.

**Comment by creationix** [comment]
Fixed in 5c72dd608f366531065762a56ebefad4b27f85a8
