### ISSUE TITLE
the remote process is not killed when the local ssh process is killed

### ISSUE THREAD

**Issue by fjakobs** [c9/vfs#8]
(SSH)

When the server is killed while a remote process is running the remote process does not get killed. In the old c9 shh code I used the "-t" -"t" arguments to force ssh to create a pseudo terminal. That way the remote processes were killed because the connected terminal disappeared. However this seems to break VFS.

**Comment by fjakobs** [comment]
Maybe the remote worker can detect the connection loss and kill itself?

**Comment by creationix** [comment]
I can't reproduce this on linux at all.  What is the exact situation that causes this problem?  What os for master and slave, what command, how is the ssh process killed?

**Comment by fjakobs** [comment]
I run both sides on my local OSX machine using the build in ssh. Then I spawn a node app on the worker which runs forever. When I Ctrl-C the master the spawned process keeps running. I think I've seen this on Solaris as well.

**Comment by fjakobs** [comment]
fixed that one
